# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\tux.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(417, 341)
        Dialog.setMinimumSize(QtCore.QSize(417, 341))
        Dialog.setMaximumSize(QtCore.QSize(417, 341))
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(115, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 0, 1, 1)
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setMinimumSize(QtCore.QSize(151, 80))
        self.frame.setAutoFillBackground(False)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(6, 2, 151, 80))
        self.label.setMinimumSize(QtCore.QSize(151, 80))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("lib/gplv3-with-text-136x68.png"))
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.frame, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(115, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 2, 1, 1)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(Dialog)
        self.plainTextEdit.setStyleSheet("background-color: rgb(89, 89, 89);\n"
"color: rgb(255, 255, 255);")
        self.plainTextEdit.setReadOnly(True)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.gridLayout.addWidget(self.plainTextEdit, 1, 0, 1, 3)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Tux Lisans"))
        self.plainTextEdit.setPlainText(_translate("Dialog", "Tux özgür bir yazılımdır, Özgür Yazılım Vakfı\'nın yayınladığı GNU Genel Kamu Lisansı\'nın 3. veya daha sonraki sürümlerindeki şartlar altında dağıtılabilir ve/veya değiştirilebilir. \n"
"\n"
"Tux faydalı olacağı umut edilerek dağıtılmaktadır, fakat HİÇBİR GARANTİSİ YOKTUR; hatta ÜRÜN DEĞERİ ya da BİR AMACA UYGUNLUK gibi garantiler de vermez. Lütfen daha çok ayrıntı için GNU Genel Kamu Lisansı\'nı inceleyin. \n"
"\n"
"Tux ile beraber GNU Genel Kamu Lisansını da almış olmalısınız; eğer almadıysanız, https://www.gnu.org/licenses/ adresine bakın."))


class Ui_MainWindow(object):
    def lisans_gui(self):
        Dialog = QtWidgets.QDialog()
        ui = Ui_Dialog()
        ui.setupUi(Dialog)
        Dialog.show()
        Dialog.exec_()

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(451, 550)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 0, 0, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout.addWidget(self.comboBox, 0, 1, 1, 2)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 1, 1, 1, 2)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.comboBox_2 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_2.setObjectName("comboBox_2")
        self.gridLayout.addWidget(self.comboBox_2, 2, 1, 1, 2)
        self.label_27 = QtWidgets.QLabel(self.centralwidget)
        self.label_27.setObjectName("label_27")
        self.gridLayout.addWidget(self.label_27, 3, 0, 1, 1)
        self.comboBox_4 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_4.setObjectName("comboBox_4")
        self.gridLayout.addWidget(self.comboBox_4, 3, 1, 1, 2)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 4, 0, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout.addWidget(self.lineEdit_2, 4, 1, 1, 2)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 5, 0, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout.addWidget(self.lineEdit_3, 5, 1, 1, 2)
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 6, 0, 1, 1)
        self.lineEdit_8 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.gridLayout.addWidget(self.lineEdit_8, 6, 1, 1, 2)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 7, 0, 1, 1)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.gridLayout.addWidget(self.lineEdit_5, 7, 1, 1, 2)
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 8, 0, 1, 1)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.gridLayout.addWidget(self.lineEdit_6, 8, 1, 1, 2)
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 9, 0, 1, 1)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.gridLayout.addWidget(self.lineEdit_7, 9, 1, 1, 2)
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setObjectName("label_18")
        self.gridLayout.addWidget(self.label_18, 10, 0, 1, 1)
        self.comboBox_10 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_10.setObjectName("comboBox_10")
        self.gridLayout.addWidget(self.comboBox_10, 10, 1, 1, 2)
        self.label_30 = QtWidgets.QLabel(self.centralwidget)
        self.label_30.setObjectName("label_30")
        self.gridLayout.addWidget(self.label_30, 11, 0, 1, 1)
        self.lineEdit_16 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.gridLayout.addWidget(self.lineEdit_16, 11, 1, 1, 2)
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 12, 0, 1, 1)
        self.comboBox_16 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_16.setObjectName("comboBox_16")
        self.gridLayout.addWidget(self.comboBox_16, 12, 1, 1, 2)
        self.label_67 = QtWidgets.QLabel(self.centralwidget)
        self.label_67.setObjectName("label_67")
        self.gridLayout.addWidget(self.label_67, 13, 0, 1, 1)
        self.comboBox_30 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_30.setObjectName("comboBox_30")
        self.gridLayout.addWidget(self.comboBox_30, 13, 1, 1, 2)
        self.label_65 = QtWidgets.QLabel(self.centralwidget)
        self.label_65.setObjectName("label_65")
        self.gridLayout.addWidget(self.label_65, 14, 0, 1, 1)
        self.lineEdit_34 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_34.setObjectName("lineEdit_34")
        self.gridLayout.addWidget(self.lineEdit_34, 14, 1, 1, 2)
        self.label_61 = QtWidgets.QLabel(self.centralwidget)
        self.label_61.setObjectName("label_61")
        self.gridLayout.addWidget(self.label_61, 15, 0, 1, 1)
        self.lineEdit_33 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_33.setObjectName("lineEdit_33")
        self.gridLayout.addWidget(self.lineEdit_33, 15, 1, 1, 2)
        self.label_62 = QtWidgets.QLabel(self.centralwidget)
        self.label_62.setObjectName("label_62")
        self.gridLayout.addWidget(self.label_62, 16, 0, 1, 1)
        self.lineEdit_35 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_35.setObjectName("lineEdit_35")
        self.gridLayout.addWidget(self.lineEdit_35, 16, 1, 1, 2)
        self.label_63 = QtWidgets.QLabel(self.centralwidget)
        self.label_63.setObjectName("label_63")
        self.gridLayout.addWidget(self.label_63, 17, 0, 1, 1)
        self.lineEdit_37 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_37.setObjectName("lineEdit_37")
        self.gridLayout.addWidget(self.lineEdit_37, 17, 1, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(292, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 18, 0, 1, 2)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 18, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 451, 21))
        self.menubar.setObjectName("menubar")
        self.menuM_teriler = QtWidgets.QMenu(self.menubar)
        self.menuM_teriler.setObjectName("menuM_teriler")
        self.menuGemiler = QtWidgets.QMenu(self.menubar)
        self.menuGemiler.setObjectName("menuGemiler")
        self.menuB_lgeler = QtWidgets.QMenu(self.menubar)
        self.menuB_lgeler.setObjectName("menuB_lgeler")
        self.menuPersonel_Bilgisi = QtWidgets.QMenu(self.menubar)
        self.menuPersonel_Bilgisi.setObjectName("menuPersonel_Bilgisi")
        self.menuAyarlar = QtWidgets.QMenu(self.menubar)
        self.menuAyarlar.setObjectName("menuAyarlar")
        self.menuYak_tlar = QtWidgets.QMenu(self.menubar)
        self.menuYak_tlar.setObjectName("menuYak_tlar")
        self.menuTeslimat = QtWidgets.QMenu(self.menubar)
        self.menuTeslimat.setObjectName("menuTeslimat")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionYeni_M_teri_Ekle = QtWidgets.QAction(MainWindow)
        self.actionYeni_M_teri_Ekle.setObjectName("actionYeni_M_teri_Ekle")
        self.actionM_teri_D_zenle = QtWidgets.QAction(MainWindow)
        self.actionM_teri_D_zenle.setObjectName("actionM_teri_D_zenle")
        self.actionM_teri_Sil = QtWidgets.QAction(MainWindow)
        self.actionM_teri_Sil.setObjectName("actionM_teri_Sil")
        self.actionGemi_Ekle = QtWidgets.QAction(MainWindow)
        self.actionGemi_Ekle.setObjectName("actionGemi_Ekle")
        self.actionGemi_Bilgii_D_zenle = QtWidgets.QAction(MainWindow)
        self.actionGemi_Bilgii_D_zenle.setObjectName("actionGemi_Bilgii_D_zenle")
        self.actionGemi_Sil = QtWidgets.QAction(MainWindow)
        self.actionGemi_Sil.setObjectName("actionGemi_Sil")
        self.actionB_lge_Ekle = QtWidgets.QAction(MainWindow)
        self.actionB_lge_Ekle.setObjectName("actionB_lge_Ekle")
        self.actionYer_Ekle = QtWidgets.QAction(MainWindow)
        self.actionYer_Ekle.setObjectName("actionYer_Ekle")
        self.actionB_lge_Yer_Sil = QtWidgets.QAction(MainWindow)
        self.actionB_lge_Yer_Sil.setObjectName("actionB_lge_Yer_Sil")
        self.actionPersonel_Ekle = QtWidgets.QAction(MainWindow)
        self.actionPersonel_Ekle.setObjectName("actionPersonel_Ekle")
        self.actionPersonel_Sil = QtWidgets.QAction(MainWindow)
        self.actionPersonel_Sil.setObjectName("actionPersonel_Sil")
        self.actionAyarlar_D_zenle = QtWidgets.QAction(MainWindow)
        self.actionAyarlar_D_zenle.setObjectName("actionAyarlar_D_zenle")
        self.actionYak_t_Ekle = QtWidgets.QAction(MainWindow)
        self.actionYak_t_Ekle.setObjectName("actionYak_t_Ekle")
        self.actionYak_t_Sil = QtWidgets.QAction(MainWindow)
        self.actionYak_t_Sil.setObjectName("actionYak_t_Sil")
        self.actionYard_m = QtWidgets.QAction(MainWindow)
        self.actionYard_m.setObjectName("actionYard_m")
        self.actionHakk_nda = QtWidgets.QAction(MainWindow)
        self.actionHakk_nda.setObjectName("actionHakk_nda")
        self.menuM_teriler.addAction(self.actionYeni_M_teri_Ekle)
        self.menuM_teriler.addAction(self.actionM_teri_D_zenle)
        self.menuM_teriler.addAction(self.actionM_teri_Sil)
        self.menuGemiler.addAction(self.actionGemi_Ekle)
        self.menuGemiler.addAction(self.actionGemi_Bilgii_D_zenle)
        self.menuGemiler.addAction(self.actionGemi_Sil)
        self.menuB_lgeler.addAction(self.actionB_lge_Ekle)
        self.menuB_lgeler.addAction(self.actionB_lge_Yer_Sil)
        self.menuPersonel_Bilgisi.addAction(self.actionPersonel_Ekle)
        self.menuPersonel_Bilgisi.addAction(self.actionPersonel_Sil)
        self.menuAyarlar.addAction(self.actionAyarlar_D_zenle)
        self.menuYak_tlar.addAction(self.actionYak_t_Ekle)
        self.menuYak_tlar.addAction(self.actionYak_t_Sil)
        self.menuTeslimat.addAction(self.actionYard_m)
        self.menuTeslimat.addAction(self.actionHakk_nda)
        self.menubar.addAction(self.menuM_teriler.menuAction())
        self.menubar.addAction(self.menuGemiler.menuAction())
        self.menubar.addAction(self.menuB_lgeler.menuAction())
        self.menubar.addAction(self.menuPersonel_Bilgisi.menuAction())
        self.menubar.addAction(self.menuYak_tlar.menuAction())
        self.menubar.addAction(self.menuAyarlar.menuAction())
        self.menubar.addAction(self.menuTeslimat.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.actionHakk_nda.triggered.connect(self.lisans_gui)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Tux"))
        self.label_14.setText(_translate("MainWindow", "Danışman"))
        self.comboBox.setItemText(0, _translate("MainWindow", "OPET"))
        self.comboBox.setItemText(1, _translate("MainWindow", "ARMARİN"))
        self.label.setText(_translate("MainWindow", "Müşteri Kodu"))
        self.label_3.setText(_translate("MainWindow", "Gemi Adı"))
        self.label_27.setText(_translate("MainWindow", "Yakıt Türü"))
        self.label_4.setText(_translate("MainWindow", "Yoğunluk"))
        self.label_5.setText(_translate("MainWindow", "Sipariş Miktarı"))
        self.label_11.setText(_translate("MainWindow", "Sıcaklık"))
        self.label_8.setText(_translate("MainWindow", "V.C.F  (T54)"))
        self.label_9.setText(_translate("MainWindow", "Litre"))
        self.label_10.setText(_translate("MainWindow", "Kilogram"))
        self.label_18.setText(_translate("MainWindow", "Teslimatçı"))
        self.label_30.setText(_translate("MainWindow", "Yakıt Alan Gemi C/E"))
        self.label_12.setText(_translate("MainWindow", "Terminal Yetkilisi"))
        self.label_67.setText(_translate("MainWindow", "Bölge"))
        self.label_65.setText(_translate("MainWindow", "Başlama Saati"))
        self.label_61.setText(_translate("MainWindow", "Bitiş Saati"))
        self.label_62.setText(_translate("MainWindow", "Opet Numune Mühür"))
        self.label_63.setText(_translate("MainWindow", "Müşteri Numune Mühür"))
        self.pushButton.setText(_translate("MainWindow", "Oluştur"))
        self.menuM_teriler.setTitle(_translate("MainWindow", "Müşteriler"))
        self.menuGemiler.setTitle(_translate("MainWindow", "Gemiler"))
        self.menuB_lgeler.setTitle(_translate("MainWindow", "Bölgeler"))
        self.menuPersonel_Bilgisi.setTitle(_translate("MainWindow", "Personel Bilgisi"))
        self.menuAyarlar.setTitle(_translate("MainWindow", "Ayarlar"))
        self.menuYak_tlar.setTitle(_translate("MainWindow", "Yakıtlar"))
        self.menuTeslimat.setTitle(_translate("MainWindow", "Yardım"))
        self.actionYeni_M_teri_Ekle.setText(_translate("MainWindow", "Yeni Müşteri Ekle"))
        self.actionM_teri_D_zenle.setText(_translate("MainWindow", "Müşteri Düzenle"))
        self.actionM_teri_Sil.setText(_translate("MainWindow", "Müşteri Sil"))
        self.actionGemi_Ekle.setText(_translate("MainWindow", "Gemi Ekle"))
        self.actionGemi_Bilgii_D_zenle.setText(_translate("MainWindow", "Gemi Bilgii Düzenle"))
        self.actionGemi_Sil.setText(_translate("MainWindow", "Gemi Sil"))
        self.actionB_lge_Ekle.setText(_translate("MainWindow", "Bölge Ekle"))
        self.actionYer_Ekle.setText(_translate("MainWindow", "Yer Ekle"))
        self.actionB_lge_Yer_Sil.setText(_translate("MainWindow", "Bölge  Sil"))
        self.actionPersonel_Ekle.setText(_translate("MainWindow", "Personel Ekle"))
        self.actionPersonel_Sil.setText(_translate("MainWindow", "Personel Sil"))
        self.actionAyarlar_D_zenle.setText(_translate("MainWindow", "Ayarları Düzenle"))
        self.actionYak_t_Ekle.setText(_translate("MainWindow", "Yakıt Ekle"))
        self.actionYak_t_Sil.setText(_translate("MainWindow", "Yakıt Sil"))
        self.actionYard_m.setText(_translate("MainWindow", "Tux Yardım"))
        self.actionHakk_nda.setText(_translate("MainWindow", "Tux Hakkında"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
